#!/bin/sh

# Init scripts are executed with "start" argument when system boots and with "stop" argument during shutdown
# So we need to check that it's boot state, not shutdown
[ -z "$1" ] || [ "$1" == "start" ] || exit 0

source "/etc/preinit"
script_init
ls  -l "$squashfs$gamepath" | grep 'CLV-P-' | awk '{ print $9 }' | while read gamecode; do
  if [ -f "/media/hakchi/boxart/$gamecode.png" ]; then
    mount -o bind "/media/hakchi/boxart/$gamecode.png" "$squashfs$gamepath/${gamecode}/${gamecode}.png"
  fi
  if [ -f "/media/hakchi/boxart/${gamecode}_small.png" ]; then
    mount -o bind "/media/hakchi/boxart/${gamecode}_small.png" "$squashfs$gamepath/${gamecode}/${gamecode}_small.png"
  fi
  if [ -f "/media/hakchi/boxart/$gamecode.desktop" ]; then
    cp -r "/media/hakchi/boxart/$gamecode.desktop" "/media/hakchi/${gamecode}/${gamecode}.desktop"
  fi
done < /dev/stdin



